### ISSUE TITLE
Tag all the things with "creator"

### ISSUE THREAD

**Issue by perbergland-meltwater** [meltwater/rabbit-puppy#1]
I'd like all persistent things like exchanges, queues etc tagged with metadata so we know that it was rabbit-puppy that created it (and what time, maybe some version if we could get a convention around that)

**Comment by remen** [comment]
:+1:

**Comment by SveTob** [comment]
This is a good use case. To accomplish this in an _un-opinionated_ way, we should allow the configuration to contain defaults for exchanges/queues/bindings per vhost, see #4. Then, you can put any argument in there that you would like, including 'creator:rabbit-puppy'.

**Comment by SveTob** [comment]
Closed, let's try #4 and see if it's a good way to do this.
